import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NavBar } from "./components";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="kanit-regular">
        <section className="p-7 md:px-10 lg:px-14 bg-azure-blue md:bg-cotton-white">
          <NavBar />
        </section>
        {children}
      </body>
    </html>
  );
}
